### ISSUE TITLE
Display category selection based from questCategories collection

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#10]
Create questCategories collection with fields:
1. name
2. description
3. status

- [x] Add rules for this new collection: read=true and write=false
- [x] Populate with collection with these categories:
CERTIFICATION
CORE - INFOR SPECIFIC
CORE - SOFT SKILL
PRODUCT SPECIFIC - FUNCTIONAL
PRODUCT SPECIFIC - TECHNICAL

- [x] Create categories service to query all available categories
- [x] Modify Add Quest modal to show categories selection via categories service
- [x] Change playerQuest.category type to be a category object
- [x] Adjust other pages displaying category

**Comment by nbcp** [comment]
Now ready for testing on staging.

**Comment by JoanBaraquiel** [comment]
On Update Quest, there are instances that the suggestions for QuestName are not appearing.
