### ISSUE TITLE
Scripts to create user badges for those who qualifies even before the badges are ready

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#104]
- [x] ~Identify badges and all their requirements to make sure nothing is missed~
- [x] Good Work
  - Monthly EXP should be >= 50
- [x] CSotH / ASotH / DSotH
  - 1 / 2 / 3 Special Quests Respectively
  - A person would 3 SQs for instance should have ALL three badges

**Comment by fjgallard** [comment]
Link to script: 
https://inforonline-my.sharepoint.com/:u:/g/personal/francisjomer_gallardo_infor_com/EZeY4dYggL9HktcODCAx41MBM-H3TiV0fOqg3irowgOJ4A?e=gN60Ak

**Comment by nbcp** [comment]
Done
