### ISSUE TITLE
Create Initial Counter for points and quests

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#106]
WHEN | THEN
-- | --
Quest is approved | Update playerPoints to include these ff info: ![image](https://user-images.githubusercontent.com/11013464/62262503-8a754980-b44b-11e9-8c0b-c863695c27ed.png)

### What we need for the one-off script:
1. Loop thru each completed quest prior to given date.
2. Update playerPoints counters

**Comment by aronpadolina** [comment]
Initial ETA;
Development: 4 hours
Code Review: 2 hours
Testing: 2 hours

**Comment by nbcp** [comment]
I just realized that we'll need a script to update this field too for all prior completed quests. Since badges will rely on this to check if their criteria is met, having incorrect past data will screw up the logic.
