### ISSUE TITLE
Standardized quest frontend changes

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#11]
- [x] Enforce category selection first
- [x] Create quest autocomplete based on selected category [good starting reference](https://angularfirebase.com/lessons/autocomplete-search-with-angular4-and-firebase/)
   - perform search to when atleast 3 characters are entered
   - search after 500ms delay of no key is entered to prevent hammering the backend too much
- [x] Save playerQuest with quest object if quest is chosen from the autocomplete
- [x] Otherwise, start first with saving it as new quest under the chosen category and coreTag=false and then saving playerQuest using the new quest 
- [x] Adjust other pages displaying quest name to use quest.name property instead
- [x] Adjust emails displaying quest name to use quest.name property instead
- [x] Disable source textbox when standard quest has been selected
- [x] Clear out quest name when category is changed

depends on #10 & #13

**Comment by JoanBaraquiel** [comment]
Upon entering the first three characters on QuestName there was no drop down of suggested Quest Names and Quest Source was auto-filled even if the QuestName Text Box is empty.
![image](https://user-images.githubusercontent.com/51430213/59898215-607b4100-9422-11e9-8f06-8c0566bc56c2.png)
![image](https://user-images.githubusercontent.com/51430213/59898224-6a9d3f80-9422-11e9-826f-3ff4b0a5a748.png)

**Comment by JoanBaraquiel** [comment]
Do you have a minimum and maximum number of characters on the questName Text Box and questSource Text Box? and also is number and special characters are acceptable?
![image](https://user-images.githubusercontent.com/51430213/59913336-8f0d1200-944a-11e9-9d32-bc7d59de118f.png)

**Comment by JoanBaraquiel** [comment]
Do you accept space as input on questName Text Box and questSource Text Box?
![image](https://user-images.githubusercontent.com/51430213/59913708-3a1dcb80-944b-11e9-95e3-513ecf4f0358.png)

**Comment by JoanBaraquiel** [comment]
On adding new quest, there is a season suggestion on the drop down of Quest Source 
![image](https://user-images.githubusercontent.com/51430213/59913819-8701a200-944b-11e9-8774-2d02255efaee.png)

**Comment by JoanBaraquiel** [comment]
On Updating Quest, QuestCategory, QuestName and QuestSource are immediately updated even though "Update Quest" button is not yet clicked. This happened right after I selected a new QuestName and whenever I clicked on the background.

**Comment by JoanBaraquiel** [comment]
Moreover, I already tested the QuestName text box and Quest Source text box. They are working properly now.
