### ISSUE TITLE
Scholar Badge

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#125]
GIVEN | WHEN | THEN
-- | -- | --
Player has submitted 1 Required Quest | Approver approves the Required Quest | Player gets one “Scholar“ badge

Note: Unlimited number

**Comment by edanga** [comment]
ETA: 
development: 2 hours
code review: 1 hour
testing: 1 hour

**Comment by JoanBaraquiel** [comment]
The testing on this ticket was done by Michaela. 

- Player submitted 1 required quest
- Approver approved the submitted quest, Player earned 10 XP
![image](https://user-images.githubusercontent.com/51430213/67740348-70e69c80-fa50-11e9-89c0-859a64f78821.png)

- Player should get a "Scholar" badge, 
![image](https://user-images.githubusercontent.com/51430213/67740436-c15dfa00-fa50-11e9-9da1-5cf9265a6a50.png)
