### ISSUE TITLE
Standardized quest collection and service

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#13]
- [x] create quests collection with the ff fields:
1. id
2. name
3. description
4. status (boolean always true for now)
5. source
6. category (object containing id, name, description, & status)
7. coreTag - true if it is uploaded

- [x] Add rules for this new collection: read=true and write=false
- [x] Prepare a csv to be used to populate this collection with data
- [x] create a new interface for quest using the above fields
- [x] create new quest service with methods:
      1. to query quests under a given category, limit to 5 results per query to reduce no. of reads [good starting reference](https://angularfirebase.com/lessons/autocomplete-search-with-angular4-and-firebase/)
      2. to save a new quest and return new quest id with coreTag=false

**Comment by nbcp** [comment]
We need to update the quest upload script here because I've change our searching algorithm in #36.
The reason why is because I noticed that startAt & endAt search strategy, only searches correctly when the input search can be found at the start of the string with all character cases matching correctly. The new strategy we'll be using is to store an array of lowercase keywords derive from all the words from the quest name. Then we can perform search against those keywords using array-contains

**Comment by aronpadolina** [comment]
Done. I just have to commit the sample csv.
Question though. Is there going to be a limit as to how many keywords can can there be per quest record?
