### ISSUE TITLE
Update My Profile Page to handle multiple teams

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#15]
- [x] Approvers that are also players would have a profile page as below:
![image](https://user-images.githubusercontent.com/11013464/58850819-a9ad6000-86c2-11e9-98d7-266bf70be2cf.png)
Where team name is based from the team where they are just a player.

- [x] Approvers that aren't players would have a profile page as below:
![image](https://user-images.githubusercontent.com/11013464/58850794-85ea1a00-86c2-11e9-8763-52b987662fb7.png)

- [x] Remove Exp for non-Players
- [x] Remove "Team Lead" Icon
- [x] Remove Quest table for non-Players
- [x] Remove "No Team Yet" moniker

**Comment by fjgallard** [comment]
Do we have a ticket for having the "Join a Team" nav-item option if the user is an approver, but NOT yet a player? 

Otherwise will have to make the instance of being an approver on a team and a player on another on console first.

**Comment by nbcp** [comment]
we don't have that because we assume for now that teams are setup from the start and only new players would need the join team page.

**Comment by fjgallard** [comment]
Oh, another thing, related to the review, but on the second picture, should we keep the subtitle for the team blank when viewing profile of Approvers who aren't players, or would putting "No Team Yet", same behavior as previous, be the desired outcome? Thanks!

**Comment by nbcp** [comment]
closed in ac2f8b5
