### ISSUE TITLE
Update Manage Quests page to handle multiple team submissions

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#16]
The requirements have been updated. The manage quest page should now contain a team selection drop down and the page should only show the quests awaiting approval for the currently selected team.

![image](https://user-images.githubusercontent.com/3413329/59810600-a065f980-9338-11e9-9791-58c80f37ad42.png)

depends on #8

**Comment by gerarrd** [comment]
`/*
  * Return ALL of the memberships, including approver memberships.
  */
  getAllMemberships(uid: string): Observable<Membership[]> {
    const playerMemberships: AngularFirestoreCollection<Membership>
      = this.afs.collection('membership', ref => ref.where('uid', '==', uid));

    return playerMemberships.snapshotChanges().pipe(
      map((members) => members.map(item => item.payload.doc.data()) )
    );
  }`

@nbcp @fjgallard 
This method gets all memberships of a given user even if that membership is not yet approved. This method was the one used for getting all of the memberships of a team lead for the manage team page. I am thinking that this method was used for getting all of the memberships of a given user when they are applying for a team. Should I create another method instead?
