### ISSUE TITLE
Angular 9 upgrade

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#172]
**Is your feature request related to a problem? Please describe.**
Angular 7 is a little bit outdated already. Need to upgrade to benefit from performance improvements and latest angular material. 

**Describe the solution you'd like**
fix/cleanup npm dependencies and do `ng update`

**Additional context**
Make sure all basic actions still works

**Comment by kaeleding** [comment]
This migration checklist might be helpful :)
https://update.angular.io/#7.0:9.0
