### ISSUE TITLE
Cannot approve quest

### ISSUE THREAD

**Issue by pbunjan** [nbcp/leaderboard#178]
**Describe the bug**
Cannot approve quest, not yet completed quest

**To Reproduce**
Go to Manage Quest (as a Lead)
Click quest
Approve
See error

**Expected behavior**
Quest is approved;
Actual result doesn't have any result.

**Screenshots**
Console error
![image](https://user-images.githubusercontent.com/53465214/80694400-0bf72680-8b07-11ea-8dc0-ea52844b3b5a.png)

**Comment by nbcp** [comment]
Isolated case, not sure how this happened. teamName field is missing on playerQuest, probably we missed them when we did #110 before. Fixed by adding the missing field. Should be reopened if reoccurs
