### ISSUE TITLE
Team Lead can't Kick a Player

### ISSUE THREAD

**Issue by JoanBaraquiel** [nbcp/leaderboard#27]
Kick "Gerome Fernandez"

1. Click "Kick" button 
![image](https://user-images.githubusercontent.com/51430213/59251637-dc280180-8c5c-11e9-8f5f-64226c984ade.png)

2. Click "Yes" on the Dialog Box to be able to Kick the Player
![image](https://user-images.githubusercontent.com/51430213/59251736-1d201600-8c5d-11e9-994a-7ffb8cc8724e.png)

3. Unable to "Kick" Gerome Fernandez
![image](https://user-images.githubusercontent.com/51430213/59251771-2f9a4f80-8c5d-11e9-92d3-45a6562ffe31.png)

**Comment by nbcp** [comment]
this case will be covered in #26 right?

**Comment by nbcp** [comment]
fixed by #26
