### ISSUE TITLE
Season ID is hardcoded string

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#30]
`auth.service.ts` and `user-profile.component.ts` are both still using a static season id from a property called PLACEHOLDER_SEASON

**Comment by JoanBaraquiel** [comment]
I created a quest for this season(Test Season)
![image](https://user-images.githubusercontent.com/51430213/60234086-67e49380-98d5-11e9-879f-f01af3e2f7bb.png)

I choose another season(Test Season1) and tested if the quest that I created in the first image will show on this season(Test Season1). Apparently, the quest that I created on the "Test Season" showed on the drop-down as suggestion but it also showed that it was a "New" quest
![image](https://user-images.githubusercontent.com/51430213/60234216-dd506400-98d5-11e9-97ab-a0d575be62f0.png)

**Comment by nbcp** [comment]
this is actually intended, it would still be tagged as new as long as you don't select from the suugested options.
