### ISSUE TITLE
Special Quest Type

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#60]
Need a new Quest Type named: Special
We need to convert button toggle into a dropdown to choose among 3 types: Required, Additional, Special
Then assign 20XP for Special Types

Changes should be at:

- [x] approveQuest at _player-quest.service_
- [x] possibly change required attribute at _player-quest.d.ts_ or add a special attribute
- [x] addQuestDialog component to add the dropdown and change logic
- [x] Remove Required / Additional Tab
- [x] Add pipe to compute new Exp on the player-quest-list component
- [x] Handle Emails

**Comment by fjgallard** [comment]
ETA:
Development: 6 hours
Code Review: 2 hours

**Comment by fjgallard** [comment]
@nbcp Should we change the _required_ attribute on PlayerQuest from boolean to string? Or should we add a new _special_ boolean attribute that we set to true instead? The latter is definitely safer and will not introduce regressions.

On the other hand, if they are going to add more Quest types tho, might be a good idea to just change the attribute.

**Comment by nbcp** [comment]
I suggest to make it an enum instead: 
0 - additional
1 - required
2 - special
adding more types would then be easy as well as changing names

**Comment by fjgallard** [comment]
Code for Script that adds a type depending on the required property: https://github.com/fjgallard/leaderboard-quest-type-conversion

**Comment by JoanBaraquiel** [comment]
Done testing this.
