### ISSUE TITLE
Update TeamsService to support teamId + uid as identifier

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#8]
Update TeamsService to use teamId + uid as reference for the ff methods:
- addMembership
- addToTeam
- getMembership
- removeTeamMember

May also need to adjust classes calling these methods

**Comment by JoanBaraquiel** [comment]
Can I test this? I think this ticket is a back-end one so it is not testable

**Comment by nbcp** [comment]
closed in ac2f8b5
