### ISSUE TITLE
Quest Name rejects the characters [.] and [:]

### ISSUE THREAD

**Issue by fjgallard** [nbcp/leaderboard#86]
![bug](https://user-images.githubusercontent.com/39758342/61672411-1a194a80-ad1e-11e9-931d-92827cc8cbb3.jpg)

**Comment by nbcp** [comment]
Yup one of the validations for free form creation of quests is to not allow special characters. 
I think we would need to modify it to accept them as long as there are still valid words inside the text (not just purely special characters)

**Comment by fjgallard** [comment]
I see. Do we need a list of valid strings to allow (such as Ming.le:)?

**Comment by nbcp** [comment]
We need a smarter regex to check for this one. Since we build keywords to search based-off at least 3 character words, we should at least expect a single word occurrence to accept a string with special characters as valid.
