### ISSUE TITLE
Update App Logo

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#91]
Need to update the images in the following locations: (please make sure they still follow their respective dimensions)
- src/favico.ico
- src/assets/icons/**
- src/assets/images/**

This will be the new logo to be used:
![Reinforce-logo](https://user-images.githubusercontent.com/11013464/62268467-90c2f000-b462-11e9-9255-5373c0622695.png)

**Comment by pbunjan** [comment]
Initial ETA:
Development: 1 day
Code Review: 1 day
QA/Testing: 1 day

**Comment by pbunjan** [comment]
should I update also images on src/assets/images/icons/**  ?
