### ISSUE TITLE
You’re on a roll! Badge

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#97]
GIVEN | WHEN | THEN
-- | -- | --
Player currently have 2 “Well done!“ Badges within the quarter | Player gets a 3rd “Well done!“ Badge within the quarter | Player gets a “You’re on a roll!!“ badge for the current quarter

**Note:** Only 4 quarters per season: May-July, Aug - Oct, Nov - Jan, and Feb - April

**Comment by nbcp** [comment]
depends on #98

**Comment by Mics05** [comment]
Upon testing the "You're in a roll" Badge, the player did not received this badge after having three well done badges.

STEPS:
-Submit one certification with required quest type
-Submit two certifications with additional quest type


![image](https://user-images.githubusercontent.com/57123036/70882423-b3693600-200a-11ea-82a9-a823cb9c9cb7.png)
