### ISSUE TITLE
Well done! Badge

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#98]
GIVEN | WHEN | THEN
-- | -- | --
Player has submitted 1 Certification Quest | Approver approves the Certification Quest | Player gets one “Well done!“ badge

**Note:** Unlimited number

**Comment by pbunjan** [comment]
ETA:
6 hrs: development
2 hrs: QA/Testing
2 hrs: Code review

**Comment by JoanBaraquiel** [comment]
Upon testing this on staging, "Well done" Badge does not appear on the earned badges.

- Complete Certification Quests
![image](https://user-images.githubusercontent.com/51430213/70615037-9d442a00-1c46-11ea-8ddc-291d94447d94.png)


- Earned Badges
![image](https://user-images.githubusercontent.com/51430213/70615101-ba78f880-1c46-11ea-92e8-5f3ff8652d84.png)

**Comment by pbunjan** [comment]
Thank you @JoanBaraquiel for the test result. As we checked earlier with @nbcp, I think we already saw the error that caused not to award the well-done badge. He/I will update this ticket when there's progress.

Thanks

**Comment by JoanBaraquiel** [comment]
Alright. Thank you too @pbunjan  :)

**Comment by nbcp** [comment]
@JoanBaraquiel the issue here has already been resolved and now available in staging. Please test all badges we have available so far to ensure we didn't miss anything else and then you may approve #142 for the release. Thank you
