### ISSUE TITLE
Good work! Badge

### ISSUE THREAD

**Issue by nbcp** [nbcp/leaderboard#99]
GIVEN | WHEN | THEN 
-- | -- | -- 
Player doesn’t have a “Good work!” badge in the current month | Player earns points that makes his/her monthly XP reach 50XP | Player receives a “Good work!” badge AND a raffle ticket for the current month

**Comment by jasminemirabueno** [comment]
ETA:
6 hrs: development
2 hrs: QA/Testing
2 hrs: Code review
